name: 'BCI_IV2a'
home: './data/BCI_IV2a'
dataset: 'BNCI2014_001'
n_subjects: 9
subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9]
sfreq: 250
n_channels: 26
eeg_channels: ['Fz', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'P1', 'Pz', 'P2', 'POz']
eog_channels: ['EOG1', 'EOG2', 'EOG3']
unify_annotations:
  # GDF numeric codes:
  "769": "left_hand"
  "770": "right_hand"
  "771": "feet"
  "772": "tongue"
  # synonyms:
  "foot": "feet"
  "left": "left_hand"
  "hand_left": "left_hand"
  "right": "right_hand"
  "hand_right": "right_hand"
event_markers:
  left_hand: 1
  right_hand: 2
  feet: 3
  tongue: 4
preprocessing:
  remove_eog_artifacts: true
  show_ica_plots: false     # if true, show interactive plots
  save_ica_plots: false      # if true, save them to disk
  ica_plots_dir: "./ica_plots"
  raw_preprocessors:
    bandpass_filter:
      kwargs:
        low: 4
        high: 38
        method: 'iir'
        notch_freq: 50
  epoching:
    kwargs:
      tmin: 2.0         # start 500 ms before the cue
      tmax: 6.0          # end 4.0 s after the cue (total epoch = 4.5 s)
      crop_window_length: 2.0    # each sliding-window crop is 2.0 s long
      crop_step_size: 0.5     # shift by 1 sample at 250 Hz (≈0.004 s)
      baseline: null
  data_split:
    kwargs:
      train_session: "0train"
      test_session: "1test"
  exponential_moving_standardization:
    kwargs:
      apply_on: "training"
      smoothing_factor: 0.1

# (Other sections like model, training, experiment settings, etc.)
model:
  name: 'deep4net'  # or 'deep4net', 'shallowfbcspnet'
  # model-specific hyperparameters...

experiment:
  n_runs: 10
  evaluation_metrics:
    - 'accuracy'
    - 'kappa'
    - 'confusion_matrix'

clustering:
  method: "kmeans"
  kmeans:
    n_clusters: 3
    init: "k-means++"
    max_iter: 300
    n_init: 10
    random_state: 42
  hierarchical:
    n_clusters: 3
    linkage: "ward"
    affinity: "euclidean"
  dbscan:
    eps: 1.0
    min_samples: 5
    metric: "euclidean"
    leaf_size: 30

tracker:
  wandb_project: 'bci_iv2a_project'
  wandb_mode: 'online'
