name: "deep4net"

#in_chans: 22 # excluding EOG and stim
in_chans: 8 # new dataset
n_classes: 3
#n_times: 500  
n_times: 600  # new dataset
final_conv_length: auto 

single:
  drop_prob: 0.25
  n_filters_time: 25
  n_filters_spat: 25
  filter_time_length: 10
  pool_time_length: 3
  pool_mode: "mean"  # mean or max

pooled:
  drop_prob: 0.25
  n_filters_time: 25
  n_filters_spat: 25
  filter_time_length: 10
  pool_time_length: 3
  pool_mode: "max"  # mean or max
  