feature_extraction:
  methods:
#    - name: erd_ers
#      kwargs:
#        baseline_window: [0.0, 0.5]
#        analysis_window: [0.5, 4.0]
#        frequency_bands:
#          mu: [8, 12]
#          beta: [13, 30]

#    - name: csp
#      kwargs:
#        frequency_band: [8, 30]
#        n_components: 4

    - name: fbcsp
      kwargs:
        frequency_bands:
          - [4, 8]
          - [8, 12]
          - [12, 16]
          - [16, 20]
          - [20, 24]
          - [24, 28]
          - [28, 32]
          - [32, 38]
        n_components_per_band: 2   # extract two spatial filters per frequency band.

    #- name: riemannian
     # kwargs:
      #  estimator: "oas"
       # mapping: "tangent"
  
  dimensionality_reduction:
    name: pca
    kwargs:
      explained_variance: 0.95

feature_selection:
  #name: lasso
  #kwargs:
    #alpha: 0.01

  #name: elasticnet
  #kwargs:
    #alphas: [0.001, 0.01, 0.1, 1.0, 10.0]
    #l1_ratios: [0.1, 0.5, 0.9]
    #cv: 5
    #scoring: neg_mean_squared_error

  name: rfecv
  kwargs:
    step: 30
    cv: 3
    scoring: accuracy
    min_features_to_select: 10
    #param_grid:
      #estimator__C: [0.1, 1.0, 10.0] 
    svc_C: 1.0  # for the internal linear SVC.
        
output_file: "./dump/1vs2/complex/features.pkl"