name: 'BCI_IV2a'
home: './data/BCI_IV2a'
dataset: 'BNCI2014_001'

n_subjects: 9
subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9]
sfreq: 250
n_channels: 26
eeg_channels: ['Fz', 'FC3', 'FC1', 'FCz', 'FC2', 'FC4', 'C5', 'C3', 'C1', 'Cz', 'C2', 'C4', 'C6', 'CP3', 'CP1', 'CPz', 'CP2', 'CP4', 'P1', 'Pz', 'P2', 'POz']
eog_channels: ['EOG1', 'EOG2', 'EOG3']

unify_annotations:
event_markers:
  left_hand: 1
  right_hand: 2
  feet: 3
  tongue: 4
  # GDF numeric codes:
  "769": "left_hand"
  "770": "right_hand"
  "771": "feet"
  "772": "tongue"
  # synonyms:
  "foot": "feet"
  "left": "left_hand"
  "hand_left": "left_hand"
  "right": "right_hand"
  "hand_right": "right_hand"

preprocessing:
  remove_eog_artifacts: true
  show_ica_plots: false     
  save_ica_plots: false     
  ica_plots_dir: "./ica_plots"
  
  ica:
    kwargs:
      n_components: 22
      method: "fastica"
      random_state: 42
  raw_preprocessors:
    bandpass_filter:
      kwargs:
        low: 4
        high: 38
        method: 'iir'
        #notch_freq: 50

  epoching:
    kwargs:
      tmin: 2.0        
      tmax: 6.0        
      crop_window_length: 2.0 
      crop_step_size: 0.5     
      baseline: null

  data_split:
    kwargs:
      train_session: "0train"
      test_session: "1test"

  exponential_moving_standardization:
    kwargs:
      smoothing_factor: 0.1
      eps: 1e-5

  output_file: "./dump/preprocessed_data.pkl"

tracker:
  wandb_project: 'bci_iv2a_project'
  wandb_mode: 'online'
